version: '3.3'

networks:
  agent-internal:
  hostnet:

services:

  mqtt-broker:
    build:
      context: ../../services/agent/mqtt-broker
      dockerfile: ./Dockerfile.mac
      args:
        NPM_TOKEN: ${NPM_TOKEN}
    environment:
      - DEBUG=${DEBUG:-trace,debug,info,warn,error,fatal}
      - MQTT_URL=mqtt://mqtt-broker:1883
    restart: always
    privileged: true
    networks:
      - agent-internal
      - hostnet
    volumes:
      - ../../services/agent/mqtt-broker:/usr/src/service
      - /usr/local/lib/node_modules:/usr/local/lib/node_modules

  signing-api:
    build:
      context: ../../services/agent/signing-api
      dockerfile: ./Dockerfile.mac
      args:
        NPM_TOKEN: ${NPM_TOKEN}
    depends_on:
      - mqtt-broker
      - signing-service
    environment:
      - DEBUG=${DEBUG:-trace,debug,info,warn,error,fatal}
      - MQTT_URL=mqtt://mqtt-broker:1883
      - PORT=80
      - SERIAL=${AGENT_SERIAL}
    ports:
      - "80:80"
    restart: always
    privileged: true
    networks:
      - agent-internal
      - hostnet
    volumes:
      - ../../services/agent/signing-api:/usr/src/service
      - /usr/local/lib/node_modules:/usr/local/lib/node_modules
      # - /usr/local/lib/node_modules/@gridplus/agent-messaging-client:/usr/local/lib/node_modules/@gridplus/agent-messaging-client

  signing-service:
    build:
      context: ../../services/agent/signing-service
      dockerfile: ./Dockerfile.mac
      args:
        NPM_TOKEN: ${NPM_TOKEN}
    depends_on:
      - mqtt-broker
    environment:
      - DEBUG=${DEBUG:-trace,debug,info,warn,error,fatal}
      - MQTT_SERVER_HOST=${MQTT_SERVER_HOST:-mqtt-broker}
      - MQTT_SERVER_PORT=${MQTT_SERVER_PORT:-1883}
      - SERIAL=${AGENT_SERIAL}
    restart: always
    privileged: true
    networks:
      - agent-internal
      - hostnet
    volumes:
      - ../../services/agent/signing-service:/usr/src/service
      - /tmp:/tmp
      - /usr/local/lib/node_modules:/usr/local/lib/node_modules
