version: '2.1'

services:

  base:
    image: docker.gridpl.us/gridplus/node-build
    environment:
      - NPM_CONFIG_REGISTRY=${NPM_CONFIG_REGISTRY}
      - NPM_TOKEN=${NPM_TOKEN}
    volumes:
      - .:/usr/src/service
    working_dir: /usr/src/service

  install:
    extends:
      service: base
    volumes:
      - .:/usr/src/service
      # - /usr/local/lib/node_modules:/usr/local/lib/node_modules
      # - /usr/local/lib/node_modules/@gridplus/node-crypto:/usr/local/lib/node_modules/@gridplus/node-crypto
      # - /usr/local/lib/node_modules/@gridplus/react-native-crypto:/usr/local/lib/node_modules/@gridplus/react-native-crypto
    command: npm i

  test:
    extends:
      service: base
    volumes:
      - .:/usr/src/service
      # - /usr/local/lib/node_modules:/usr/local/lib/node_modules
      # - /usr/local/lib/node_modules/@gridplus/node-crypto:/usr/local/lib/node_modules/@gridplus/node-crypto
      # - /usr/local/lib/node_modules/@gridplus/react-native-crypto:/usr/local/lib/node_modules/@gridplus/react-native-crypto
    command: npm test
