version: '3.4'

networks:
  agent-internal:
  hostnet:

services:

  bcoin:
    build:
      context: .
      dockerfile: bcoin.Dockerfile
    restart: always
    ports:
      - "48332:48332"
      - "48333:48333"
    environment:
      BCOIN_CONFIG: /conf/bcoin.conf
      VIRTUAL_HOST: localhost
      VIRTUAL_PORT: 48332
    volumes:
      - ./.bcoin:/data
      - ./support/bcoin/bcoin.conf:/conf/bcoin.conf

  ganache:
    image: trufflesuite/ganache-cli:latest
    ports:
      - "8545:8545"
    command: "--host 0.0.0.0 --mnemonic \"finish oppose decorate face calm tragic certain desk hour urge dinosaur mango\""

  mqtt-broker:
    build:
      context: ../../services/agent/mqtt-broker
      dockerfile: ./Dockerfile.mac
      args:
        NPM_TOKEN: ${NPM_TOKEN}
    environment:
      - DEBUG=${DEBUG:-trace,debug,info,warn,error,fatal}
      - MQTT_URL=mqtt://mqtt-broker:1883
    restart: always
    privileged: true
    networks:
      - agent-internal
      - hostnet
    volumes:
      - ../../services/agent/mqtt-broker:/usr/src/service
      - /usr/local/lib/node_modules:/usr/local/lib/node_modules

  signing-api:
    build:
      context: ../../services/agent/signing-api
      dockerfile: ./Dockerfile.mac
      args:
        NPM_TOKEN: ${NPM_TOKEN}
    depends_on:
      - mqtt-broker
      - signing-service
    environment:
      - DEBUG=${DEBUG:-trace,debug,info,warn,error,fatal}
      - MQTT_URL=mqtt://mqtt-broker:1883
      - PORT=80
      - AGENT_SERIAL=${AGENT_SERIAL}
    ports:
      - "80:80"
    restart: always
    privileged: true
    networks:
      - agent-internal
      - hostnet
    volumes:
      - ../../services/agent/signing-api:/usr/src/service
      - /usr/local/lib/node_modules:/usr/local/lib/node_modules

  signing-service:
    build:
      context: ../../services/agent/signing-service
      dockerfile: ./Dockerfile.mac
      args:
        NPM_TOKEN: ${NPM_TOKEN}
    depends_on:
      - mqtt-broker
    environment:
      - DEBUG=${DEBUG:-trace,debug,info,warn,error,fatal}
      - MQTT_SERVER_HOST=${MQTT_SERVER_HOST:-mqtt-broker}
      - MQTT_SERVER_PORT=${MQTT_SERVER_PORT:-1883}
      - AGENT_SERIAL=${AGENT_SERIAL}
    restart: always
    privileged: true
    networks:
      - agent-internal
      - hostnet
    volumes:
      - ../../services/agent/signing-service:/usr/src/service
      - /tmp:/tmp
      - /usr/local/lib/node_modules:/usr/local/lib/node_modules

  signing-proxy-api:
    build:
      context: ../../services/signing-proxy-api
      dockerfile: ./Dockerfile.mac
      args:
        NPM_TOKEN: ${NPM_TOKEN}
    environment:
      - DEBUG=${DEBUG:-trace,debug,info,warn,error,fatal}
      - MQTT_URL=mqtt://mqtt-broker:1883
      - PORT=3000
    ports:
      - "3000:3000"
    restart: always
    privileged: true
    networks:
      - hostnet
    volumes:
      - ../../services/signing-proxy-api:/usr/src/service
      - /usr/local/lib/node_modules:/usr/local/lib/node_modules